-- ─────────────────────────────────────────────────────────────────────────────
-- BlockDegree — Complete Supabase PostgreSQL Schema
-- Run in: Supabase Dashboard → SQL Editor → New Query → Run
-- ─────────────────────────────────────────────────────────────────────────────

-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: users
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id                    UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  name                  VARCHAR(200)  NOT NULL,
  email                 VARCHAR(255)  UNIQUE NOT NULL,
  password_hash         VARCHAR(255)  NOT NULL,
  role                  VARCHAR(20)   NOT NULL
                          CHECK (role IN ('admin','university','student','employer')),

  -- Student fields
  student_id            VARCHAR(100),

  -- University fields
  institution_id        UUID,
  institution_name      VARCHAR(200),

  -- Wallet (MetaMask MFA — optional)
  wallet_address        VARCHAR(42),

  -- Face verification
  -- Stored as JSON string of float[128]
  -- Selected explicitly only when needed — never auto-returned
  face_descriptor       TEXT,
  face_descriptor_hash  VARCHAR(64),
  face_registered_at    TIMESTAMPTZ,

  -- Account state
  is_active             BOOLEAN       NOT NULL DEFAULT true,
  email_verified        BOOLEAN       NOT NULL DEFAULT false,
  avatar_url            TEXT,
  last_login            TIMESTAMPTZ,
  metadata              JSONB         DEFAULT '{}',

  created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_email       ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role        ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_student_id  ON users(student_id);
CREATE INDEX IF NOT EXISTS idx_users_institution ON users(institution_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: degrees
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS degrees (
  id                      UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Student information
  student_name            VARCHAR(200)  NOT NULL,
  student_id              VARCHAR(100)  NOT NULL,
  graduate_id             UUID          REFERENCES users(id) ON DELETE SET NULL,
  graduate_email          VARCHAR(255),

  -- Degree details
  degree_title            VARCHAR(300)  NOT NULL,
  field_of_study          VARCHAR(300)  NOT NULL,
  graduation_date         DATE          NOT NULL,
  gpa                     DECIMAL(4,2)  CHECK (gpa >= 0 AND gpa <= 4.0),
  honors                  VARCHAR(100),
  metadata                JSONB         DEFAULT '{}',

  -- Institution
  institution_id          UUID          NOT NULL,
  institution_name        VARCHAR(200),
  issued_by               UUID          REFERENCES users(id) ON DELETE SET NULL,

  -- ── CRYPTOGRAPHIC SPINE ───────────────────────────────────────────────────
  -- SHA-256 of normalised credential fields.
  -- IMMUTABLE after issuance. This is what gets stored on blockchain.
  degree_hash             VARCHAR(64)   UNIQUE NOT NULL,

  -- Certificate number (auto-generated by trigger)
  certificate_number      VARCHAR(100)  UNIQUE,

  -- Lifecycle status
  status                  VARCHAR(20)   NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending','issued','revoked','suspended')),

  -- Blockchain synchronisation tracking
  blockchain_sync_status  VARCHAR(20)   NOT NULL DEFAULT 'queued'
                            CHECK (blockchain_sync_status IN
                              ('queued','processing','success','failed','queue_error')),
  blockchain_tx_hash      VARCHAR(66),
  blockchain_block_number BIGINT,
  blockchain_timestamp    BIGINT,

  -- Revocation
  revocation_reason       TEXT,
  revoked_at              TIMESTAMPTZ,
  revocation_tx_hash      VARCHAR(66),

  -- QR code (Base64 DataURL — cached after first generation)
  qr_code_url             TEXT,

  -- IPFS — decentralised document storage
  -- Answers the examiner question: "What if Supabase is compromised?"
  -- The degree PDF lives on IPFS. The CID is stored on the blockchain.
  ipfs_cid                VARCHAR(200),
  ipfs_gateway_url        TEXT,
  document_hash           VARCHAR(64),
  document_url            TEXT,

  created_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_degrees_student_id      ON degrees(student_id);
CREATE INDEX IF NOT EXISTS idx_degrees_degree_hash     ON degrees(degree_hash);
CREATE INDEX IF NOT EXISTS idx_degrees_institution_id  ON degrees(institution_id);
CREATE INDEX IF NOT EXISTS idx_degrees_status          ON degrees(status);
CREATE INDEX IF NOT EXISTS idx_degrees_bc_sync         ON degrees(blockchain_sync_status);
CREATE INDEX IF NOT EXISTS idx_degrees_graduate_id     ON degrees(graduate_id);
CREATE INDEX IF NOT EXISTS idx_degrees_created_at      ON degrees(created_at DESC);

-- Auto-generate certificate number on insert
CREATE SEQUENCE IF NOT EXISTS certificate_seq START 100000 INCREMENT 1;

CREATE OR REPLACE FUNCTION generate_certificate_number()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.certificate_number IS NULL THEN
    NEW.certificate_number :=
      'BD-' || TO_CHAR(NOW(), 'YYYY') || '-' ||
      LPAD(NEXTVAL('certificate_seq')::TEXT, 6, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_cert_number ON degrees;
CREATE TRIGGER trg_cert_number
  BEFORE INSERT ON degrees
  FOR EACH ROW EXECUTE FUNCTION generate_certificate_number();

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_degrees_updated_at ON degrees;
CREATE TRIGGER trg_degrees_updated_at
  BEFORE UPDATE ON degrees
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: verification_logs
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS verification_logs (
  id                  UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  computed_hash       VARCHAR(64),
  result              VARCHAR(20)   NOT NULL
                        CHECK (result IN ('valid','invalid','revoked')),
  verifier_id         UUID          REFERENCES users(id) ON DELETE SET NULL,
  verifier_ip         VARCHAR(45),
  degree_id           UUID          REFERENCES degrees(id) ON DELETE SET NULL,
  verification_method VARCHAR(20)
                        CHECK (verification_method IN ('hash','qr','ocr','face')),
  on_chain_record     JSONB         DEFAULT '{}',
  metadata            JSONB         DEFAULT '{}',
  verified_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vlog_hash      ON verification_logs(computed_hash);
CREATE INDEX IF NOT EXISTS idx_vlog_degree    ON verification_logs(degree_id);
CREATE INDEX IF NOT EXISTS idx_vlog_result    ON verification_logs(result);
CREATE INDEX IF NOT EXISTS idx_vlog_ip        ON verification_logs(verifier_ip);
CREATE INDEX IF NOT EXISTS idx_vlog_date      ON verification_logs(verified_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: audit_logs
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_logs (
  id          UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  action      VARCHAR(100)  NOT NULL,
  actor_id    UUID          REFERENCES users(id) ON DELETE SET NULL,
  actor_role  VARCHAR(20),
  target_id   TEXT,
  target_type VARCHAR(50),
  details     JSONB         DEFAULT '{}',
  ip_address  VARCHAR(45),
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alog_actor   ON audit_logs(actor_id);
CREATE INDEX IF NOT EXISTS idx_alog_action  ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_alog_date    ON audit_logs(created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: fraud_logs
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS fraud_logs (
  id              UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  file_name       VARCHAR(500),
  file_hash       VARCHAR(64),
  fraud_score     INTEGER       NOT NULL DEFAULT 0
                    CHECK (fraud_score BETWEEN 0 AND 100),
  risk_level      VARCHAR(20)   NOT NULL DEFAULT 'MINIMAL'
                    CHECK (risk_level IN ('MINIMAL','LOW','MEDIUM','HIGH','CRITICAL')),
  is_fraudulent   BOOLEAN       NOT NULL DEFAULT false,
  findings        JSONB         NOT NULL DEFAULT '[]',
  breakdown       JSONB         DEFAULT '{}',
  yolo_detections JSONB         DEFAULT '{}',
  ocr_confidence  DECIMAL(5,2),
  reported_by     UUID          REFERENCES users(id) ON DELETE SET NULL,
  degree_id       UUID          REFERENCES degrees(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fraud_flag   ON fraud_logs(is_fraudulent);
CREATE INDEX IF NOT EXISTS idx_fraud_risk   ON fraud_logs(risk_level);
CREATE INDEX IF NOT EXISTS idx_fraud_date   ON fraud_logs(created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: face_verification_logs
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS face_verification_logs (
  id          UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id     UUID          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  distance    DECIMAL(6,4)  NOT NULL,
  confidence  INTEGER       NOT NULL CHECK (confidence BETWEEN 0 AND 100),
  is_match    BOOLEAN       NOT NULL,
  threshold   DECIMAL(4,2)  DEFAULT 0.60,
  provider    VARCHAR(50)   DEFAULT 'face-api-local',
  verified_at TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fvlog_user  ON face_verification_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_fvlog_match ON face_verification_logs(is_match);
CREATE INDEX IF NOT EXISTS idx_fvlog_date  ON face_verification_logs(verified_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: ipfs_documents
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ipfs_documents (
  id            UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  degree_id     UUID          REFERENCES degrees(id) ON DELETE SET NULL,
  user_id       UUID          REFERENCES users(id)   ON DELETE SET NULL,
  cid           VARCHAR(200)  NOT NULL UNIQUE,
  local_hash    VARCHAR(64)   NOT NULL,
  gateway_url   TEXT,
  pinata_url    TEXT,
  file_size     BIGINT,
  file_type     VARCHAR(100),
  document_type VARCHAR(50)   DEFAULT 'degree'
                  CHECK (document_type IN ('degree','transcript','cnic','selfie','other')),
  is_pinned     BOOLEAN       DEFAULT true,
  created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ipfs_degree ON ipfs_documents(degree_id);
CREATE INDEX IF NOT EXISTS idx_ipfs_cid    ON ipfs_documents(cid);
CREATE INDEX IF NOT EXISTS idx_ipfs_user   ON ipfs_documents(user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: documents   <--- ADDED (was missing)
-- Stores uploaded user documents (CNIC, marksheets, certificates) with
-- OCR, YOLO, and validation statuses.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS documents (
  id                    UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id               UUID          REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  degree_id             UUID          REFERENCES degrees(id) ON DELETE SET NULL,
  document_type         VARCHAR(50)   NOT NULL DEFAULT 'degree',
  file_name             VARCHAR(255)  NOT NULL,
  original_name         VARCHAR(255)  NOT NULL,
  file_path             TEXT          NOT NULL,
  file_url              TEXT          NOT NULL,
  file_size             BIGINT,
  mime_type             VARCHAR(100),
  file_hash             VARCHAR(64)   UNIQUE NOT NULL,

  -- OCR data
  ocr_data              JSONB         DEFAULT '{}',
  ocr_confidence        DECIMAL(5,2)  DEFAULT 0,
  ocr_status            TEXT          DEFAULT 'pending',
  ocr_text              TEXT,

  -- YOLO / layout analysis
  yolo_status           TEXT          DEFAULT 'pending',
  yolo_detections       TEXT[]        DEFAULT '{}',
  yolo_valid            BOOLEAN,
  yolo_confidence       FLOAT,

  -- Validation against user profile
  validation_status     TEXT          DEFAULT 'pending',
  validation_errors     TEXT[]        DEFAULT '{}',
  extracted_data        JSONB         DEFAULT '{}',

  -- Fraud detection
  fraud_score           INTEGER       DEFAULT 0 CHECK (fraud_score BETWEEN 0 AND 100),
  is_verified           BOOLEAN       DEFAULT false,
  verification_notes    TEXT,

  -- Timestamps
  created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_docs_user_id    ON documents(user_id);
CREATE INDEX IF NOT EXISTS idx_docs_type       ON documents(document_type);
CREATE INDEX IF NOT EXISTS idx_docs_hash       ON documents(file_hash);
CREATE INDEX IF NOT EXISTS idx_docs_created    ON documents(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_docs_ocr_status ON documents(ocr_status);
CREATE INDEX IF NOT EXISTS idx_docs_yolo_status ON documents(yolo_status);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: blockchain_transactions
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS blockchain_transactions (
  id           UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  tx_hash      VARCHAR(66)   UNIQUE NOT NULL,
  degree_id    UUID          REFERENCES degrees(id) ON DELETE SET NULL,
  operation    VARCHAR(50)   NOT NULL
                 CHECK (operation IN ('issue','revoke','verify')),
  status       VARCHAR(20)   NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending','confirmed','failed')),
  block_number BIGINT,
  gas_used     VARCHAR(50),
  created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  confirmed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_bctx_hash      ON blockchain_transactions(tx_hash);
CREATE INDEX IF NOT EXISTS idx_bctx_degree_id ON blockchain_transactions(degree_id);
CREATE INDEX IF NOT EXISTS idx_bctx_status    ON blockchain_transactions(status);

-- ─────────────────────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
-- Service role bypasses RLS automatically.
-- Application-level role enforcement is done in controllers + roleMiddleware.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE degrees              ENABLE ROW LEVEL SECURITY;
ALTER TABLE verification_logs    ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs           ENABLE ROW LEVEL SECURITY;
ALTER TABLE fraud_logs           ENABLE ROW LEVEL SECURITY;
ALTER TABLE ipfs_documents       ENABLE ROW LEVEL SECURITY;
ALTER TABLE face_verification_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents            ENABLE ROW LEVEL SECURITY;   -- newly added

-- ─────────────────────────────────────────────────────────────────────────────
-- Ensure all columns exist (idempotent) – in case table already existed
-- without the new columns, this will add them.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.documents 
  ADD COLUMN IF NOT EXISTS ocr_status TEXT DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS yolo_status TEXT DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS validation_status TEXT DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS ocr_text TEXT,
  ADD COLUMN IF NOT EXISTS ocr_confidence NUMERIC,
  ADD COLUMN IF NOT EXISTS extracted_data JSONB DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS yolo_detections JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS yolo_valid BOOLEAN,
  ADD COLUMN IF NOT EXISTS yolo_confidence NUMERIC,
  ADD COLUMN IF NOT EXISTS validation_errors JSONB DEFAULT '[]',
  -- Keep legacy fields (may already exist)
  ADD COLUMN IF NOT EXISTS ocr_data JSONB DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS fraud_score NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS verification_notes TEXT;